kind: BuildConfig
apiVersion: v1
metadata:
  name: weblogic
spec:
  triggers:
    - type: ImageChange
  source:
    type: Git
    git:
      uri: "https://github.com/spikehip/weblogic-ose.git"
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: "oraclelinux:7"
  output: 
    to:
      kind: ImageStreamTag
      name: "weblogic:12c"
